### PR TITLE
Add `include()` Fix function.

### LINKED ISSUE #12: Facilitate composability (file inclusion)
* Allow Fixes to include other Fix files (cf. [Metamorph: Splitting Metamorph Definitions for Reuse](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#splitting-metamorph-definitions-for-reuse)).
* Included files are evaluated in-place at the time of inclusion.
* Possibly allow parameters to be passed to the included file.

```
include(path_to_fix, params...)
```

### PR DESCRIPTION
**Pull request by blackwinter**
Resolves #12.

_Base branch will be changed automatically once #124 is merged._

### CODE REVIEW

File: metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java [hunk 1]
```diff
@@ -132,6 +142,195 @@ public void shouldDoNothing() {
...
+                o -> {
+                }
+            )
+        );
+    }
+
+    @Test
+    public void shouldIncludeFixFileFromExternalScript() {
+        MetafixTestHelpers.assertFix(streamReceiver, Arrays.asList(
+                "src/test/resources/org/metafacture/metafix/fixes/include.fix"
```
Comment (fsteeg) [inline metafix/src/test/java/org/metafacture/metafix/MetafixScriptTest.java:261]: Quite unexpected usage of what I only thought of a flux feature :-)

**Review by fsteeg — APPROVED** [review]
