### PR TITLE
Use the default option as in catmandu #333

### LINKED ISSUE #333: Lookup option default does not work
See example here:

https://metafacture.org/playground/?flux=inputFile%0A%7C+open-file%0A%7C+as-records%0A%7C+decode-yaml%0A%7C+fix%28transformationFile%29%0A%7C+encode-yaml%0A%7C+print%0A%3B%0A&transformation=put_map%28%22typeMap%22%2C%0A++%22dog%22%3A+%22mammal%22%2C%0A++%22parrot%22%3A+%22bird%22%2C%0A++%22shark%22%3A+%22fish%22%0A%29%0A%0Acopy_field%28%22animal%22%2C%22type%22%29%0A%0Alookup%28%22type%22%2C%22typeMap%22%2C+_default%3A%22other%22%29%0A&data=---%0Aanimal%3A+dog%0A%0A---%0Aanimal%3A+parrot%0A%0A%0A---%0Aanimal%3A+shark%0A%0A---%0Aanimal%3A+crab

### PR DESCRIPTION
**Pull request by TobiasNx**
Resolves #333.

### CODE REVIEW

File: metafix/src/main/java/org/metafacture/metafix/FixMethod.java [hunk 1]
```diff
@@ -530,8 +531,11 @@ public void apply(final Metafix metafix, final Record record, final List<String>
                     if (c != null) {
                         c.accept(oldValue);
                     }
-
+                    elsif (defaultOption != null){
```
Comment (blackwinter) [inline metafix/src/main/java/org/metafacture/metafix/FixMethod.java:534]: This branch will not be reached when `print_unknown="true"`.

File: metafix/src/main/java/org/metafacture/metafix/FixMethod.java [hunk 2]
```diff
@@ -530,8 +531,11 @@ public void apply(final Metafix metafix, final Record record, final List<String>
...
+                        return defaultOption;
+                    }
                     return defaultValue != null ? defaultValue : delete ? null : oldValue;
```
Comment (blackwinter) [inline metafix/src/main/java/org/metafacture/metafix/FixMethod.java:537]:
```suggestion
                    return defaultOption != null ? defaultOption : defaultValue != null ? defaultValue : delete ? null : oldValue;
```

As [previously suggested](https://github.com/metafacture/metafacture-fix/issues/333#issuecomment-1801984070), this would be even better though (at the top of the method):

```java
final String defaultValue = options.getOrDefault(Maps.DEFAULT_MAP_KEY, map.get(Maps.DEFAULT_MAP_KEY));
```

It would allow you to specify the default value _per lookup call_ in addition to _per map_. The next step would then be to decide whether we want to keep supporting the Metamorph syntax (`__default`) or switch to the Catmandu syntax (`default`). Or even support both (which seems a little messy, though).

File: metafix/src/main/java/org/metafacture/metafix/FixMethod.java [hunk 3]
```diff
@@ -530,8 +531,11 @@ public void apply(final Metafix metafix, final Record record, final List<String>
...
+
```
Comment (blackwinter) [inline metafix/src/main/java/org/metafacture/metafix/FixMethod.java:538]: Please don't add/remove empty lines in existing code ;)

**Review by blackwinter — CHANGES_REQUESTED** [review]

**Comment by TobiasNx** [comment]
@blackwinter  could you help me how I would continue here? I would suggest to drop the `_default` version of metamorph.

**Comment by blackwinter** [comment]
I've changed the default handling according to our last discussion:

* `default` from options.
* `__default` from map.

(27634d1)

Still needs tests and documentation.

**Comment by TobiasNx** [comment]
@blackwinter I added tests and tried them locally but they still seem to fail:

```
MetafixLookupTest > shouldUseDefaultOptionValueIfNotFound() STANDARD_ERROR
    [Test worker] WARN org.metafacture.metafix.validation.XtextValidator - The FixStandaloneSetup file '/tmp/metafix1977380759175164437.fix' has 1 issue:
    [Test worker] WARN org.metafacture.metafix.validation.XtextValidator - - ERROR: no viable alternative at input 'default' (2:28)

MetafixLookupTest > shouldUseDefaultOptionValueIfNotFound() FAILED
    org.metafacture.metafix.FixParseException: Invalid FixStandaloneSetup resource: /tmp/metafix1977380759175164437.fix
        at app//org.metafacture.metafix.validation.XtextValidator.getValidatedResource(XtextValidator.java:73)
        at app//org.metafacture.metafix.FixStandaloneSetup.parseFix(FixStandaloneSetup.java:31)
        at app//org.metafacture.metafix.FixStandaloneSetup.parseFix(FixStandaloneSetup.java:36)
        at app//org.metafacture.metafix.Metafix.getRecordTransformer(Metafix.java:205)
        at app//org.metafacture.metafix.Metafix.<init>(Metafix.java:119)
        at app//org.metafacture.metafix.MetafixTestHelpers.fix(MetafixTestHelpers.java:151)
        at app//org.metafacture.metafix.MetafixTestHelpers.assertFix(MetafixTestHelpers.java:133)
        at app//org.metafacture.metafix.MetafixTestHelpers.assertFix(MetafixTestHelpers.java:112)
        at app//org.metafacture.metafix.MetafixLookupTest.shouldUseDefaultOptionValueIfNotFound(MetafixLookupTest.java:643)

```

**Comment by blackwinter** [comment]
Could it be that `default` is a reserved keyword and needs to be quoted (like `var`)?

File: README.md [hunk 4]
```diff
@@ -706,7 +706,7 @@ Parameters:
 
 Options:
 
-- `__default`: Default value to use for unknown values. (Default: Old value)
+- `"default"`: Default value to use for unknown values. The `"default"`-key needs to be in quotation marks since it is a reserved word in Java.  (Default: Old value)
```
Comment (blackwinter) [inline README.md:709]: Please don't mix names and syntax, the option name is "default". The fact that it (currently) has to be written as `"default"` in the Fix should not matter here. I'd be willing to accept the note, but it should be reworded (also, extra whitespace):

```suggestion
- `default`: Default value to use for unknown values. The option needs to be written in quotation marks because it is a reserved word in Java. (Default: Old value)
```

File: README.md [hunk 5]
```diff
@@ -748,7 +748,7 @@ put_rdfmap("path/to/file", "rdf-map", target: "<rdfProperty>")
 lookup("path.to.field", "rdf-map")
 
 # with default value
-lookup("path.to.field", "map-name", __default: "NA")
+lookup("path.to.field", "map-name", default: "NA")
```
Comment (blackwinter) [inline README.md:751]: The option needs to be written in quotation marks because it is a reserved word in Java.

**Review by blackwinter — CHANGES_REQUESTED** [review]

File: README.md (hunk 5 above)
Comment (TobiasNx) [reply README.md:751]:
```suggestion
lookup("path.to.field", "map-name", "default": "NA")
```

File: README.md (hunk 4 above)
Comment (TobiasNx) [reply README.md]: Done thanks. We could use the wording in #365  too.

File: README.md (hunk 5 above)
Comment (TobiasNx) [reply README.md]: Done. Thanks

**Review by blackwinter — APPROVED** [review]

**Comment by TobiasNx** [comment]
I adde @fsteeg for code review
